### ISSUE TITLE
[Question] How do I read the message of a specific user in channel chat?

### ISSUE THREAD

**Issue by Khailz** [benediktschmitt/py-ts3#12]
`event.pared[0]['msg']` gives all event messages so what about choosing a certain one?

**Comment by SentinelX101** [comment]
The parsed event includes the invokerid, invokername and invokeruid.
```
# Example of the full channel message parsed event
[{'msg': 'Test', 'invokeruid': '78i29sdWd8Ci8d32oQVClXd93ks=', 'invokerid': '2', 'targetmode': '2', 'invokername': 'SentinelX101'}]
```
All of which could be used to identify a user and only read their message, like this for example:
```
# Check who sent the message
if event.parsed[0]['invokername'] == 'SentinelX101':
    # Print the message
    print(event.parsed[0]['msg'])
```

**Comment by Khailz** [comment]
Would it be like this because I want to specify what the message needs to
 `while True:`
            `userPick = event.parsed[0]['event.parsed[0]['invokername']`
            `msg = event.parsed[0]['msg']`
            `RequestedDiceAmount = msg`

**Comment by Khailz** [comment]
I figured it all out, wasn't as hard a I thought
