### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Multivit4min** [benediktschmitt/py-ts3#14]
Hey,

i have a new Problem, whenever i run the Bot it uses a massive amount of CPU

ps aux Output:

pyts3    17633 94.8  0.4  46624  8912 pts/0    Sl+  21:28   0:12 python3 bot.py

I tested it with your Event Handling Template on my Virtual Machine with 4 GB Ram and 2 vCPUs each 3,7 GHz
CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz

I am using Python 3.2 on Debian 7

**Comment by benediktschmitt** [comment]
Hmmm, there should be no (significant) cpu load at all, when the ts3 server is idle. Do you receive a massive amount of events?

I tested the example with an idle ts3 server and there was no (significant) cpu load. (Python 3.4, Debian 8)

**Comment by Multivit4min** [comment]
I just tested it with 3.4 and the CPU is now nearly at 0%
