### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ryanbentley** [benediktschmitt/py-ts3#16]
You are using pip version 7.0.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting ts3
  Using cached ts3-0.6.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\thomas\appdata\local\temp\pip-build-iuamee\ts3\setup.py", l
ine 28, in <module>
        from ts3 import __version__
      File "ts3\__init__.py", line 45, in <module>
        import query
      File "ts3\query.py", line 43, in <module>
        from commands import TS3Commands
      File "ts3\commands.py", line 79
        def banadd(self, *, ip=None, name=None, uid=None, time=None, banreason=N
one):
                          ^

**Comment by benediktschmitt** [comment]
Hi!

is this a response for issue #15   or a new issue ?

**Comment by snoofx** [comment]
Hi!

I get the same error as @ryanbentley. I manually installed the Blinker Module but py-ts3 won't install. 
I tried the manually way "python setup.py" and "pip3 install ts3" but both are not working :/

Do you have a solution?

**Comment by benediktschmitt** [comment]
Hmm, are you using the latest pip3 version?

**Comment by benediktschmitt** [comment]
@ryanbentley Can you please add the exception type? I assume you tried to install the ts3 package with Python 2, because the syntax in this line is only supported in Python 3.

@snoofx Are you using the latest pip3 version?

**Comment by Luppii** [comment]
I had a similar (the same?) issue. You have to use Python 3. I could not install ts3 directly by invoking `pip3 install ts3`. To resolve I did the following steps:
* Upgrade pip3 (if you have < 7.1.0): `pip3 install --upgrade pip`
* Install blinker: `pip3 install blinker`
* Install ts3: `pip3 install ts3`

@benediktschmitt You should add blinker as a dependency to the ts3 package so pip will autoinstall it for you.

**Comment by benediktschmitt** [comment]
I switched to *setuptools*, so the dependencies will be installed automatically now.

Please let me know, if you have still installation problems.

**Comment by Luppii** [comment]
Running only `pip3 install ts3` now works without a hitch, just tried it out on a new machine. This issue can probably be closed.
