### ISSUE TITLE
Fails to install on python 2

### ISSUE THREAD

**Issue by PikalaxALT** [benediktschmitt/py-ts3#21]
When running `pip install ts3`:

    File "ts3/commands.py", line 79
    def banadd(self, *, ip=None, name=None, uid=None, time=None, banreason=None):
                      ^
    SyntaxError: invalid syntax

**Comment by mrandri19** [comment]
This package uses the bare asterisk syntax, which is only available for python3.
You could fork the repository to change the files and remove the asterisk since it only

**Comment by PikalaxALT** [comment]
That's what I feared. Thanks for verifying.
