### ISSUE TITLE
Memory leaking TS3QueryResponse

### ISSUE THREAD

**Issue by IdleGandalf** [benediktschmitt/py-ts3#22]
Hey,

I use your lib for a daemon that provides some functions in the TS3 chat. After a while I noticed that the process grows to a few gigs in a short period of a few days, so I checked the most common object types with objgraph and noticed that they are almost 10000 non-garbage collected objects of type TS3QueryResponse after just 15 minutes of runtime.

I don't know if this is an issue of me using something wrong because of missing documentation or a memory leak in your lib. I don't do special things with your responses and they *should* not be referenced by my code anywhere after use.

Here is the relevant output of objgraph.show_most_common_types():

> dict                       21782
> list                       20541
> TS3QueryResponse           9849

I would appreciate if you could take a look ;)

Edit: Ah and yes, I checked almost every single dict and list that I am using for possible leaks, but found none.

**Comment by benediktschmitt** [comment]
It's an issue. The connection class currently stores all received responses in *self._responses*, which is not necessary, but was faster to implement compared with threading events, when I wrote this library two years ago.
I'll try to fix it as soon as possible, without introducing any side effects.

**Comment by IdleGandalf** [comment]
I had a (very) short look into your code before I wrote this, but I have missed that, otherwise I would have come up with a PR myself.

I can't await getting that fixed, it bugged me for hours now ;) Thanks!

**Comment by benediktschmitt** [comment]
Thanks for the PR offer :)

I think I fixed it with my last commit. Please tell me if you still experience the memory leak. (The code is in the issue#22 branch)

**Comment by IdleGandalf** [comment]
Memory usage isn't moving a kilobyte now after 10mins of runtime ;) Thanks for the quick fix!

**Comment by benediktschmitt** [comment]
You're welcome. It makes me happy to know that people use my code to do something useful :)

**Comment by IdleGandalf** [comment]
Yea thats something I appreciate myself very highly ;) I'm going to release that thing I'm working on very soon here on github. If you wish I can poke you if that happens, maybe you can use (I assume you run a TS3 yourself) or just enjoy your lib in action ;)
