### ISSUE TITLE
TypeError on ts3conn.use()

### ISSUE THREAD

**Issue by Thymo-** [benediktschmitt/py-ts3#23]
I'm getting a TypeError when I try to use a server.
I'm using ts3conn.use(1) and it comes back with this:

Traceback (most recent call last):
  File "./votebot.py", line 35, in <module>
    ts3conn.use(1)
TypeError: use() takes 1 positional argument but 2 were given

Am I doing something wrong or is this a bug?

**Comment by Thymo-** [comment]
Getting the same error when I try the example.

**Comment by benediktschmitt** [comment]
All the query commands accept only keyword parameters:
```python3
ts3conn.use(sid=1)
```

This is wrong in the README, sorry .

**Comment by Thymo-** [comment]
I tried the same for use as is done in here and got it working:
https://github.com/benediktschmitt/py-ts3/pull/7
