### ISSUE TITLE
Is it possible to use this to connect to servers that are not owned by me?

### ISSUE THREAD

**Issue by MaximusPrime2015** [benediktschmitt/py-ts3#24]
Sorry if this is a dumb question, but I can't connect to any servers. Either I get an invalid loginname or password, or I get a timeout.
Thanks.

**Comment by benediktschmitt** [comment]
You can try to get a query login as described here: http://www.teamspeak3.com/support/teamspeak-3-add-server-query-user.php

I don't know, if there are other ways. The commands you are allowed to execute depend on the permission configuration of each ts3 server.

**Comment by MaximusPrime2015** [comment]
I couldn't get a login query, but thanks anyway.
