### ISSUE TITLE
Teamspeak closing connection

### ISSUE THREAD

**Issue by WhatsCS** [benediktschmitt/py-ts3#25]
I currently have a bot that does some magic but can only stay connected for the full 600 seconds before telnet disconnects it. So I have two questions, the first is, am I doing this correctly (see below) and if so, is it a bug in the code?

```python
        ts3conn.servernotifyregister(event="server")
        ts3conn.recv(True)
        ts3conn.keepalive(interval=300)
```

**Comment by benediktschmitt** [comment]
You can try to call *ts3conn.keepalive()* before *ts3conn.recv_in_thread()*. But I'm not sure if it works.

However, the event handling in the current version (0.7.x) of the library is very bad. I made some changes to fix it. You should take a look at the *dev* branch. Here's a small example of the new API:
```python
#!/usr/bin/python3

import time
import ts3

with ts3.query.TS3Connection("localhost") as ts3conn:
  ts3conn.login(
    client_login_name="serveradmin",
    client_login_password="FoOBa9"
  )
  ts3conn.use(sid=1)

  # Register for events
  ts3conn.servernotifyregister(event="server")

  # event loop
  while True:
    ts3conn.send_keepalive()
    try:
      # the timeout makes sure, we sent the keepalive message at least once in 150s.
      event = ts3conn.wait_for_event(timeout=150)
    except ts3.query.TS3TimeoutError:
      pass      
    else:
      # Greet new clients.
      if event[0]["reasonid"] == "0":
        print("client connected")
        ts3conn.clientpoke(clid=event[0]["clid"], msg="Hello :)")
```

http://py-ts3.readthedocs.io/en/dev/
https://github.com/benediktschmitt/py-ts3/tree/dev

**Comment by WhatsCS** [comment]
I see, I'll switch to the dev branch and give it a go. Thank you for the quick response!

**Comment by WhatsCS** [comment]
Due to the removal of last_resp, how should I go about doing the following?
```python
name = ts3conn.last_resp.parsed[0]['client_nickname']
```
Also it's now printing everything, such as ts3conn.whoami() to the console.

**Comment by benediktschmitt** [comment]
All query commands return the response, so you can simply write:
```python
resp = ts3conn.whoami()
name = resp[0]["client_nickname"]
```

**Comment by benediktschmitt** [comment]
I removed the *print()* calls. There should be no console output now :)

**Comment by WhatsCS** [comment]
Alright, thank you!
