### ISSUE TITLE
Create Tests Cases

### ISSUE THREAD

**Issue by benediktschmitt** [benediktschmitt/py-ts3#26]
Create some unittests.

**Comment by jlebonzec** [comment]
For which functions would you like unittests ? Maybe I could use some spare time to contribute. :)

**Comment by benediktschmitt** [comment]
Hi, that would be great. I really appreciate your help. 

I think for the start, it would be good to have some test cases for the *TS3BaseConnection* class and perhaps the *TS3Response* and *TS3FileTransfer* classes.
