### ISSUE TITLE
wait_for_event doesn't returns the event type

### ISSUE THREAD

**Issue by Aens** [benediktschmitt/py-ts3#31]
I'm new at Git, sorry if I don't do this correctly.
Ideally the dict with the event should send the event type:

> [{**'eventtype': 'notifytextmessage'**, 'invokername': '[YOLO]Aens Windstorm', 'targetmode': '2', 'msg': 'f', 'invokerid': '141', 'invokeruid': '6yj3hyXUCWt0xOUlWIh/1NpnAWo='}]

But instead it's sending everything correctly except that:

> [{'invokername': '[YOLO]Aens Windstorm', 'targetmode': '2', 'msg': 'f', 'invokerid': '141', 'invokeruid': '6yj3hyXUCWt0xOUlWIh/1NpnAWo='}]

The issue I believe it's on _recv method of query.py file

I added two lines for you to see where the event_type should be saved, because somehow magically through the code the first word that tells me what type of event I'm getting (notifytextmessage, notifyclientleftview, notifyclientmoved, etc) disappears and is not sent to the wait_for_event method, which I use to read events with a bot.
```
# We received an event.
            elif re_index == 0:
                event = TS3Event(data)
                event_type = str(data)[2:].split(" ")[0] #1 capture event type
                event[0]['eventtype'] = event_type #2 add it to the dict
                self._event_queue.append(event)
                return event
```
Is that a mistake or there is a way to capture the event type without editing your code and I just missed it?

**Comment by benediktschmitt** [comment]
Hi,

the *TS3Event* objects have a property *event*, which stores the event type: http://py-ts3.readthedocs.io/en/latest/api/response.html#ts3.response.TS3Event.event

**Comment by Aens** [comment]
My apologies, I couldn't figure out that part because it's missleading that the event type of an event is also named event and accessed through `event.event`. Maybe it would help others to document that part better. Thank you for your answer and your hard work.
