### ISSUE TITLE
Slow/stuck query execution

### ISSUE THREAD

**Issue by nifares** [benediktschmitt/py-ts3#32]
It's taking around 1 minute to return the list when you use clientdblist(duration=50)
real    1m2.498s

When you try do clientdblist(duration=100) or more it will hang.  The return time on that query via telnet tool is instant.

**Comment by benediktschmitt** [comment]
Hi, when I execute the command on my test-server, it returns the response almost immediately. This could have several reasons: My test-server only knows a few clients and the db is small (I don't know how large your db is), how long does it take, when you execute this command without waiting for events in the background (if you are waiting for them?)?

**Comment by Aens** [comment]
I can also relate to this behavior with several different commands. Tried to use clientlist yesterday with 30 users online and it took more or less 3-5 seconds. Tried today with 80 and it takes 30 seconds, check the timestamps: http://prntscr.com/c2c0i2
It also happens with channellist or servergroupclientlist(sgid=X). That last one will only works when the group I'm requesting data has few users.

Our user database is more of less of 50.000 users, and it's worth to mention that if I bypass the queue and bruteforce a telnet reading, the response is almost immediate. Hence I believe there's a bottleneck somewhere in the queue part.

**Comment by nifares** [comment]
Hi benediktschmitt,

I'm just using python script : 

resp = ts3conn.clientdblist(duration=50)
print(resp)

so with the value of 50 it takes around 60 seconds. But if I put duration=100 it will take few minutes. My teamspeak DB has around 105 entries.

**Comment by benediktschmitt** [comment]
I think the *expect()* method of the telnet connection is the bottleneck. I changed the code in the *dev* branch to use *read_until()* instead, which is a little bit faster. However, Python's telnetlib seems to be quite slow :(

Please leave a comment, if this change provides a speed gain for your programs.

**Comment by nifares** [comment]
Work like a charm now!

    teamspeakathenaLIRSpytime ./core.py
    Error: 0 ok
    lfpnifarez Nifares
    graciouslion Gra-chu
    lfpradec Radec
    lfpkacze KaczaPs
    real    0m0.387s
    user    0m0.297s
    sys     0m0.027s

**Comment by Aens** [comment]
I can also confirm this. 173 users online, it's instant and there's no delay or bottleneck: These are the timestamps: http://prntscr.com/c2i4fz
