### ISSUE TITLE
Is it possible login with custom nickname?

### ISSUE THREAD

**Issue by thusk** [benediktschmitt/py-ts3#33]
its possible set a custom nickname to login? in way of "serveradmin from 127.0.0.1" ?
i didnt see it on documentation, on php lib was possible.

thanks, Thusk.

**Comment by benediktschmitt** [comment]
I'm not sure, but I think you can use the *clientupdate* command to change the nickname.http://py-ts3.readthedocs.io/en/latest/api/commands.html#ts3.commands.TS3Commands.clientupdate after login.

**Comment by thusk** [comment]
:+1: thanks
