### ISSUE TITLE
ChannelCreate not working

### ISSUE THREAD

**Issue by Mem6000** [benediktschmitt/py-ts3#37]
Hello,
I have a problem with creating channels.
When I am doing this command:
`ts3conn.channelcreate(channel_name="test channel", channel_flag_permanent=True)`
library does't return the CID of the newly created channel, how to get it?

**Comment by pathmann** [comment]
The cid is in the TS3Response channelcreate returns.

So this should work:
```python
resp = ts3conc.channelcreate(channel_name="test channel", channel_flag_permanent=True)
print(resp[0]['cid'])
```

**Comment by Mem6000** [comment]
I have this error:
http://iv.pl/images/03632836943669694705.png

**Comment by Mem6000** [comment]
I have this error when I try to listen:
ts3conn.servernotifyregister(event="server", id_=0)
ts3conn.servernotifyregister(event="channel", id_=0) - error is related to this

**Comment by benediktschmitt** [comment]
Hi, can I close this issue?

**Comment by Najlepszy56** [comment]
The problem with servernotifyregister still occurs, but this is not a problem.
