### ISSUE TITLE
ClientQuery support

### ISSUE THREAD

**Issue by Scrxtchy** [benediktschmitt/py-ts3#48]
Might be quite of a major change to the repo, but I belive having support for this within the same package could benefit it's development, since they use the same functions, however a different or extended set of commands.
If this is going to be chased up, after a simple plan of action, I will be glad to help in development when able to

**Comment by benediktschmitt** [comment]
Hi, I only took a quick look into the manual. You're probably right: It should be sufficient to write a new [TS3Commands](https://github.com/benediktschmitt/py-ts3/blob/master/ts3/commands.py) class for the client. The [TS3BaseConnection](https://github.com/benediktschmitt/py-ts3/blob/master/ts3/query.py#L111) class can then be sub classed as done [here](https://github.com/benediktschmitt/py-ts3/blob/master/ts3/query.py#L449). The *TS3FileTransfer*, the escape module and *TS3Response* class should work for the client too. New definitions can be added to *definitions.py* if necessary.

I'll have some time to read through the README of the clientquery plugin on sunday. Any help is appreciated, but it should follow the same coding style as the current library (especially copying the documentation from the TS3 README to the command methods -_-). I think writing the TS3ClientCommand class is probably the best way to start.

**Comment by Scrxtchy** [comment]
I've written up the functions that are imlemented into clientquery, and noted which from serverquery are not in the readme docs, which is helpful as for object inheritance if that's what might happen
![image](https://user-images.githubusercontent.com/12771982/28708198-ac3424a8-73be-11e7-93b2-fcec7f5866b7.png)

Documentation isn't complete, but I also found some functions on serverquery could be updated for `**kwargs`. Can sort that out after this issue though if it's necessary

**Comment by benediktschmitt** [comment]
The Client Query API is now fully supported in version 2.0.0 using the TS3QueryBuilder.

**Comment by Scrxtchy** [comment]
Thank you kindly
