### ISSUE TITLE
Where can I find a list of events?

### ISSUE THREAD

**Issue by a6J3nETWVCnwgXjjKcNVfGBfBmsd87nP** [benediktschmitt/py-ts3#53]
Hi,

  Where can I find documentation on the kind of events the API works with? For example, you provided a demo "Hello Bot" that pokes users upon the event of a new connection -- but what about other events, such as when a user group is added or removed, a user is banned, etc?

**Comment by benediktschmitt** [comment]
Hello,

in the TS3 server's installation folder should be a directory *doc/serverquery". This directory contains a html document with all possible commands. The supported events can be found in the description for the *servernotifyregister* command.

Here is a also link to an older version: http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

**Comment by a6J3nETWVCnwgXjjKcNVfGBfBmsd87nP** [comment]
So I checked the query documentation, which wasn't helpful because they don't specify the "emitters" that `servernotifyregister `actually notifies. As it turns out, Teamspeak has terrible documentation, but, to my gratitude, I found[ this lovely site](http://yat.qa/ressourcen/server-query-notify/) that provides the list!

My struggle now is that I don't know how to have my Python code specify one of these events/emitters. I can do the basic things like `ts3conn.servernotifyregister(event="textserver")` or `ts3conn.servernotifyregister(event="channel", id_=2)` (as provided in your examples) ...

But, what about events such as `client_away` from `notifycliententerview`  or `channel_name` from `notifychannelcreated`? How do I code my script to listen for those? If you could help me figure that out, then I'll be able to work that knowledge with the rest of the other emitters.

Thank you so much.

- Scharr
