### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by regendare** [benediktschmitt/py-ts3#56]
When i try doing ts3conn.send_keepalive() or ts3conn.clientupdate(nickname="Test"), they both resolved to the same error:

self._telnet_conn.write(b"\n\r")
AttributeError: 'NoneType' object has no attribute 'write'

It appears that the self.telnet_conn has no .write attribute?

**Comment by benediktschmitt** [comment]
The *_telnet_conn* attribute is none if no connection to a ts3 server exists at the moment, i.e. no connection has been created yet or an existing connection has been closed after a fatal error. 

Without some code which produces the bug?, it's almost impossible to help. If this exception still occurs, feel free to reopen this issue.
