### ISSUE TITLE
Connection keeps getting slower after a while

### ISSUE THREAD

**Issue by WhOoKie** [benediktschmitt/py-ts3#57]
I have written two scripts. The first:
https://pastebin.com/VJck7eAh
and the second:
https://pastebin.com/tVFkwxeH

The second script just takes all clients and pushes them into a mySQL database every X minutes.
The first script writes every client a message as soon as he joins, and handles commands in a private chat.

The problem is, the first script (command handling) keeps getting slower, and you really notice it after about 30 seconds. And commands only delay it more.

The second script (mySQL interface) is running just fine, no issues there.

Any idea why? I traced the problem down to the reciever side,
so somewhere between the user sending the bot a command and the event firing the script takes longer than usual.

Any idea why? Maybe its an issue with the _recv function, or my telnet port just clogges?

**Comment by benediktschmitt** [comment]
You can use the standard Python profiler https://docs.python.org/3.6/library/profile.html to find bottlenecks. It may help here.

At a first glance at the code, you should specify a timeout in the *wait_for_event()* method, otherwise the *send_keepalive()* is not called at least once in 10 minutes. You can use something like:
```Python
  try:
    e = tsConn.wait_for_event(timeout=400)
  except TimeoutError:
   continue
```

Side note: Is there a reason why you are using **del** explicitly and not trusting Python's garbage collector?

**Comment by WhOoKie** [comment]
1) I used del just because I initially thought it was an issue with the RAM, so I deleted the variables as soon as they were not needed anymore. Just never bothered to delete the del statements afterwards.

2) Also, if I open a SQ connection manually, there is no problem. I can servernotifyregister to the private messages without a problem, and they always arrive within a couple seconds, even I really spam the messages.
So looks like it might be an issue with the wait_for_event() function?

**Comment by WhOoKie** [comment]
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
35   	0.149    0.004    0.150    0.004 <frozen importlib._bootstrap_external>:830(get_data)
1   	0.023    0.023    0.023    0.023 connections.py:254(autocommit)
70   	1.743    0.025    1.743    0.025 connections.py:268(query)
784    	0.014    0.000    0.029    0.000 telnetlib.py:422(process_rawq)
26742   0.014    0.000    0.015    0.000 telnetlib.py:494(rawq_getchar)
5    	0.071    0.014    0.081    0.016 {built-in method _imp.create_dynamic}
5    	0.071    0.014    0.081    0.016 {built-in method _imp.create_dynamic}
1    	0.045    0.045    0.064    0.064 {built-in method _socket.getaddrinfo}
258    	0.011    0.000    0.011    0.000 {built-in method nt.stat}
1    	0.026    0.026    0.026    0.026 {method 'connect' of '_socket.socket' objects}
```

Thats what I've gathered from the cProfile data... Those are all entrys with tottime > 0.010 and percall > 0.010.
Maybe it helps?

**Comment by WhOoKie** [comment]
I just tried printing all the events recieved...
```
 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E72A024E0>

 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E729DA7F0>

 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E72A024E0>

 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E729DA7F0>

 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E72A024E0>

 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E729DA7F0>

 => Started new mainloop in ts3stamm_commands.py
<ts3.response.TS3Event object at 0x0000017E72A024E0>
```

So it looks like it keeps recieving events, even though nothing happend.

**Comment by WhOoKie** [comment]
Well, I found the issue. Totally didnt think of that...
I added a message that tells you when a command doesnt exist, but that message gets triggered when the bot write the message that a command doesnt exist.
So its an infinite loop that takes up lots of space.

**Comment by benediktschmitt** [comment]
Sorry, I wasn't able to answer earlier. I'm glad you were able to find the bug.
