### ISSUE TITLE
servernotifyregister: channel id not working

### ISSUE THREAD

**Issue by githubl0ver69** [benediktschmitt/py-ts3#60]
`ts3conn.exec_("servernotifyregister", event="textchannel", id_=106)`

The command successfully listens and reports all messages within channel. However, it does not switch to the configured channel ID _(106)_ with `id `or `id_`... Am I doing something wrong? I tried this on both v1 and v2 of your API, and neither work.

**Comment by benediktschmitt** [comment]
I'm not sure if this is a problem with this library or the TS3 Server. However, you can move the query client to the target channel before starting to listen:

```Python
with ts3.query.TS3ServerConnection(host="localhost") as ts3conn:
    ts3conn.exec_("login", client_login_name="serveradmin", client_login_password="JB8ZqxfI")
    ts3conn.exec_("use", sid=1)

    resp = ts3conn.exec_("whoami")
    ts3conn.exec_("clientmove", clid=resp.parsed[0]["client_id"], cid=2)

    ts3conn.exec_("servernotifyregister", event="textchannel")
    while True:
        event = ts3conn.wait_for_event()
        print(event.parsed)
```

**Comment by githubl0ver69** [comment]
Thank you, this will work just fine.

Also I'm new to Python so excuse the noob question:

Is there a reason you use `clid=resp.parsed[0]["client_id]` instead of something like `clid=resp[0]["client_id")` ? Is it best practice or something?

**Comment by benediktschmitt** [comment]
You can use whatever you want, the second method is only a shortcut :)

-- Both ways will keep working, but I may streamline the API in the future since *resp[0]["client_id"]* does not feel very pythonic :cry:
