### ISSUE TITLE
AttributeError: module 'ts3.query' has no attribute 'TS3ServerConnection'

### ISSUE THREAD

**Issue by Bluscream** [benediktschmitt/py-ts3#62]
```
Error calling method onConnectStatusChangeEvent of plugin my Support: Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 394, in invokePlugins
    ret.append(meth(*args))
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\mySupport\__init__.py", line 61, in onConnectStatusChangeEvent
    with ts3.query.TS3ServerConnection("51.255.133.6") as ts3conn:
AttributeError: module 'ts3.query' has no attribute 'TS3ServerConnection'
```

**Comment by benediktschmitt** [comment]
Thats the name of the sever connection class in version 2. If you are using version 1, then it is simply 
*TS3Connection*. 

I renamed it to avoid confusion with the interface for the ts3 client query interface.

**Comment by Bluscream** [comment]
Ahh, i was unable to get v2 from pip, i just dropped the ts3 folder from this repo in my includes folder and it worked, thanks :)

**Comment by Bluscream** [comment]
@benediktschmitt i got it to work with
```py
                with ts3.query.TS3ServerConnection("51.255.133.6", 1976) as ts3conn:
                    err = ts3conn.query("login", client_login_name="bl", client_login_password="") # TODO: Remove before commit!
                    err = ts3conn.query("use", port=9987)
                    err = ts3conn.query("clientupdate", client_nickname="Bluscream")
                    err = ts3conn.query("channeldelete", cid=self.supchan, force=1)
```
but for some weird reason it stops working after removing the debug prints after each line :/
Does it need more time? like a sleep or smth for example?

**Comment by benediktschmitt** [comment]
No, the ``ts3conn.query("use", port=9987)`` method returns a query object. The actual query is only executed, when the result is accessed (in the print statement via __str__). So you either need to use ``ts3conn.query("use", port=9987).fetch()`` or simply ``ts3conn.exec_("use", port=9987)``.
The query object is only useful if you plan to pipe many parameters into one command.

https://github.com/benediktschmitt/py-ts3/tree/v2#ts3-query-commands

**Comment by Bluscream** [comment]
Does your example only apply to the "use" command or the others aswell?

**Comment by benediktschmitt** [comment]
To all commands. ``ts3conn.exec(...)`` is only a shortcut for ``ts3conn.query(...).fetch()``.

**Comment by Bluscream** [comment]
One last question: Why does
```py
err = ts3conn.query("use", port=self.cfg.getint("serverquery","port"))
print("[OUT] use port [IN]",err.all())
```
result in
```
[OUT] use port [IN] []
```

**Comment by benediktschmitt** [comment]
The *use* command doesn't return any values. So the list with all returned values is empty.

**Comment by Bluscream** [comment]
What would be the correct way to get the full response as string?

**Comment by benediktschmitt** [comment]
``resp.data`` or ``resp.data_bytestr``. 

-- https://py-ts3.readthedocs.io/en/v2/api/response.html

**Comment by Bluscream** [comment]
Awesome, thank you :)

**Comment by Bluscream** [comment]
It got a bit more failsafe now:
```py
                try: import ts3
                except ImportError:
                    from devtools import PluginInstaller
                    PluginInstaller().installPackages(['ts3'])
                    import ts3
                con = None
                if hasattr(ts3.query, "TS3ServerConnection"): con = ts3.query.TS3ServerConnection
                else: con = ts3.query.TS3Connection
                with con(self.cfg.get("serverquery","host"), self.cfg.getint("serverquery","qport")) as ts3conn:
                    ts3conn.query("login", client_login_name=self.cfg.get("serverquery","name"), client_login_password=self.cfg.get("serverquery","pw")).fetch()
                    ts3conn.query("use", port=self.cfg.getint("serverquery","port")).fetch()
                    ts3conn.query("clientupdate", client_nickname=self.cfg.get("serverquery","nick")).fetch()
                    ts3conn.query("channeldelete", cid=self.supchan, force=1).fetch()
```
