### ISSUE TITLE
AttributeError: module 'ts3.query' has no attribute 'TS3ServerConnection'

### ISSUE THREAD

**Issue by leon1995** [benediktschmitt/py-ts3#65]
Hi.

I used the first version and installed it with pip (and it worked) but when I want to use the second version I always get the Error `AttributeError: module 'ts3.query' has no attribute 'TS3ServerConnection'`.
Of course I installed the version with `pip3 install ts3` but it seems that only the first version works.

I hope you can help me :)

**Comment by benediktschmitt** [comment]
Hi, version 1 and 2 are not compatible. The TS3Connection class has been renamed to TS3ServerConnection in version 2 to distinguish better between the connector to the TS3 client query interface.

**Comment by leon1995** [comment]
Thanks for your quick answer.
I try to use your sayhello example from version 2. But I get this error. Your example from version1 is working. How do I upgrade to version 2? I did use `pip3 install ts3` to install your skript and `python3 myskript.py` to start my skript.
I hope you can help me with these new informations :)
