### ISSUE TITLE
TS3Channel objects?

### ISSUE THREAD

**Issue by WhOoKie** [benediktschmitt/py-ts3#68]
Its not necessarely an issue, more like a suggestion...
What about using some object orientation for the clients and the channels?
Like, when you use `conn.clientinfo(clid=1)` it doesn't return a huge dict, but rather returns an object.
That makes it easier to create channels, so you can just create a channel object and pass it to the function.
Also with a channel object people (rather me) would find it better to retrieve and create info or channels since the code completion could alredy give you the parameters and you don't have to go though that damn manual all the time.

I thought of usage like this:
```
c = ts3.ts3objects.ts3Channel()
c.channelname = "Hello123"
c.channel_talkpower = 75

cl = conn.clientinfo(clid=client, obj=True)
print(cl.clientname)
```

Probably not worth the efford since dicts are very similar, but just wanted to bring this up.

EDIT:
Maybe make some properties read only, like those which cannot be set when you want to create a channel, like the channelid?

**Comment by benediktschmitt** [comment]
I can see some benefits, but I'd prefer keeping this library as low level / general as it is. However, if you want to create a package on top of py-ts3 with an object oriented layer yourself, I could add a link to the README.
