### ISSUE TITLE
Suggestion to support release of TeamSpeak Server 3.3.0 and it's new SSH feature set.

### ISSUE THREAD

**Issue by safsfs** [benediktschmitt/py-ts3#70]
With Teamspeak's latest server update to version 3.3.0, they've added twitch integration, SSH for the server query and new command-line options. While all 3 updates having their place in, or around, your API would be nice -- I hope it's realistic and within your interest to implement the new SSH features.

I would be happy to assist with beta testing and creating a new set of examples for you, too.

**A few points to note from Teamspeak:**

> - The ssh support comes with new command line parameters, see doc/server_quickstart.txt for more information.
> - We also added history, tab-completion and keyboard shortcuts like killing, yanking and searching.
> there is a maximum of 4096 characters per input line. We might fix that in a later version.
> - Bot or admin tools connecting over ssh should not allocate a PTY, giving access to the good old query, just encrypted - and without the 4096 characters limit per input line.
> - We overhauled server query flooding. It is now more forgiving, allowing for naive implementations that still run fast.

[Forum > General Discussions > Announcements > Latest News > [Release] TeamSpeak 3 Server 3.3.0](https://forum.teamspeak.com/threads/136554)

They also include some [SSH-Query with Python](https://gist.github.com/muenchow/3b2bc8c4ea46ebdfa1222d01eaf5b3dc) examples.

**Comment by Aens** [comment]
Does this means that we'll have to re-code our bots if they don't use telnet anymore?

**Comment by JF-Dunford** [comment]
Let's pretend that never happened ^

**Comment by benediktschmitt** [comment]
@JF-Dunford What happened?

@Aens I don't intend to port the change back to v1, but if you are using v2, then only the *open* method changes (it will require a *username* and *password*). v2 will also support both, telnet *and* ssh, so you're free to use whatever protocol you want.

**Comment by benediktschmitt** [comment]
py-ts3 now fully supports SSH.
