### ISSUE TITLE
How to use clientinfo?

### ISSUE THREAD

**Issue by Bluscream** [benediktschmitt/py-ts3#81]
I must be incredibly stupid. I can't seem to figure out how to use `clientinfo` as it's not in any of the examples nor in the docs. Also it's only one time in the code (https://github.com/benediktschmitt/py-ts3/search?utf8=%E2%9C%93&q=clientinfo&type=) but if I try to find that file it doesn't exist. Only `common.py`

**Comment by AdorablePotato** [comment]
I answered in the other issue of yours with an example. The TS3 server directory contains a full, up-to-date manual in ``doc/serverquery/serverquery.html``. (It's a kinda hidden and the TS3 guys don't seem to host it on the official website - I could not find it there.).

**Comment by whookie** [comment]
They used to, I always used to view it there, but I agree, for some reason it is just not there anymore.
Although I have found the SQ documentation somewhere else:
https://github.com/marcin-/pardususer.de/blob/master/teamspeak3/files/TeamSpeak%203%20Server%20Query%20Manual.pdf

**Comment by Bluscream** [comment]
There is a finite number of commands. So I would prefer them to be properly implemented as functions otherwise I can use any telnet lib. Anyway that's out of the scope of this issue.
