### ISSUE TITLE
TS3ClientConnection connect method

### ISSUE THREAD

**Issue by saecki** [benediktschmitt/py-ts3#88]
So I don't know if just I can't find any method for connecting to a ts3 server or if there really is no specific method. I managed to connect to a server by using the send method which I see is being replaced by exec_. It functions well but isn't a clean solution at all.
Would be nice to have a connect method in the future if there isn't a similar one already that I'm to dumb to find. Thanks in advance.

**Comment by whookie** [comment]
As far as I know there is no method to connect.
The connection is opened when you create the object.

**Comment by saecki** [comment]
So maybe I wasn't quite clear with my explanation. I was talking about connecting with a teamspeak clients server connection handler to a teamspeak server not opening the telnet connection to the clientquery plugin. And I was only able to archieve this with the send method by passing connect as the command and an address parameter with the ip of the server.
