### ISSUE TITLE
Fails to run example code

### ISSUE THREAD

**Issue by rob-bb** [benediktschmitt/py-ts3#9]
Hi

I get this error with the examples. 

with ts3.query.TS3Connection("localhost") as ts3conn:
AttributeError: 'module' object has no attribute 'query'

**Comment by rob-bb** [comment]
My mistake, conflicting packages.

**Comment by JohnDooe** [comment]
Hi, I have the same  problem, witch packages make the conflict ?

thanks

**Comment by rob-bb** [comment]
I cant recall the exact details now, but they were python packages rather than ubuntu packages, so look in your python sit-packages directory for other directories named ts3, remove them then install this one.
